---

---
## Tarefa 3.4 - Análise Exploratória e Estatística Descritiva - Medidas estatísticas utilizando Pyhton

Esta tarefa consiste analisar por meio de métodos de descrição paramétrica (medidas estatísticas) o conjunto de dados *Hourly Wages*.

Você deve implementar em Python os itens solicitados abaixo utilizando a biblioteca Pandas e outras que forem necessárias.

---



---

## Conjunto de dados *Hourly Wages*

Esse conjunto de dados é popularmente empregado para a tarefa de regressão em Machine Learning. Constrói-se e ajusta-se um modelo de aprendizado de máquina para predizer/estimar o salário de um funcionário em função de suas características (anos de estudos, experiência de trabalho, filiação sindical, região, ocupação e sexo).

- Número de Instâncias: 534

- Número de Atributos: 9 atributos numéricos e o target (*wage_per_hour*)

- Informações dos Atributos:
  - union (filiação sindical)
  - education_yrs (anos de instrução)
  - experience_yrs (anos de experiência)
  - age (idade)
  - female (sexo)
  - marr (estado civil - casado)
  - south (região)
  - manufacturing (indústria)
  - construction (construção)

  
- Variável de destino (target): wage_per_hour

## Implementar os itens abaixo:

In [39]:
import pandas as pd
import numpy as np

#### a-) Clonar o repositório de dados da disciplina (DSBD) hospedado no GitHUb.

In [40]:
!git clone https://github.com/malegopc/DSBD

fatal: destination path 'DSBD' already exists and is not an empty directory.

#### b-) Ler o dataset "*Hourly_wages/hourly_wages.csv*" como dataframe utilizando a biblioteca Pandas e mostrar as 5 primeiras e as 5 últimas linhas do dataset.

In [41]:
caminho_arquivo = 'https://raw.githubusercontent.com/malegopc/DSBD/main/Datasets/Hourly_wages/hourly_wages.csv'

df_wages = pd.read_csv(caminho_arquivo)

print("--- 5 Primeiras Linhas ---")
display(df_wages.head())

print("\n--- 5 Últimas Linhas ---")
display(df_wages.tail())

--- 5 Primeiras Linhas ---

,wage_per_hour,union,education_yrs,experience_yrs,age,female,marr,south,manufacturing,construction
0,5.10,0,8,21,35,1,1,0,1,0
1,4.95,0,9,42,57,1,1,0,1,0
2,6.67,0,12,1,19,0,0,0,1,0
3,4.00,0,12,4,22,0,0,0,0,0
4,7.50,0,12,17,35,0,1,0,0,0

--- 5 Últimas Linhas ---

,wage_per_hour,union,education_yrs,experience_yrs,age,female,marr,south,manufacturing,construction
529,11.36,0,18,5,29,0,0,0,0,0
530,6.10,0,12,33,51,1,1,0,0,0
531,23.25,1,17,25,48,1,1,0,0,0
532,19.88,1,12,13,31,0,1,1,0,0
533,15.38,0,16,33,55,0,1,0,1,0

#### c-) Obter um resumo da estatística descritiva dos dados utilizando um único comando (função).

In [42]:
df_wages.describe()

,wage_per_hour,union,education_yrs,experience_yrs,age,female,marr,south,manufacturing,construction
count,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000,534.000000
mean,9.024064,0.179775,13.018727,17.822097,36.833333,0.458801,0.655431,0.292135,0.185393,0.044944
std,5.139097,0.384360,2.615373,12.379710,11.726573,0.498767,0.475673,0.455170,0.388981,0.207375
min,1.000000,0.000000,2.000000,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.250000,0.000000,12.000000,8.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.780000,0.000000,12.000000,15.000000,35.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,11.250000,0.000000,15.000000,26.000000,44.000000,1.000000,1.000000,1.000000,0.000000,0.000000
max,44.500000,1.000000,18.000000,55.000000,64.000000,1.000000,1.000000,1.000000,1.000000,1.000000

#### d-) Calcule a proporção de funcionários de sexo masculino e feminino.

In [43]:
proporcao_sexo = df_wages['female'].value_counts(normalize=True) * 100
print("Proporção por sexo (%):")
print(proporcao_sexo)

Proporção por sexo (%):
female
0    54.11985
1    45.88015
Name: proportion, dtype: float64

#### e-) Calcule a proporção de casados e solteiros.

In [44]:
proporcao_estado_civil = df_wages['marr'].value_counts(normalize=True) * 100
print("Proporção por estado civil (%):")
print(proporcao_estado_civil)

Proporção por estado civil (%):
marr
1    65.543071
0    34.456929
Name: proportion, dtype: float64

#### f-) Calcule as médias de cada uma das variáveis: anos de educação, anos de experiência e idade

In [45]:
medias = df_wages[['education_yrs', 'experience_yrs', 'age']].mean()
print("Médias:")
print(medias)

Médias:
education_yrs     13.018727
experience_yrs    17.822097
age               36.833333
dtype: float64

#### g-) Calcule as medianas de cada uma das variáveis: anos de educação, anos de experiência e idade.

In [46]:
medianas = df_wages[['education_yrs', 'experience_yrs', 'age']].median()
print("Medianas:")
print(medianas)

Medianas:
education_yrs     12.0
experience_yrs    15.0
age               35.0
dtype: float64

####h-) Calcule as modas de cada uma das variáveis: anos de educação, anos de experiência e idade.

In [47]:
modas = df_wages[['education_yrs', 'experience_yrs', 'age']].mode()
print("Modas:")
display(modas)

Modas:

   education_yrs  experience_yrs  age
0             12              14   32

####i-) Analisando especificamente a variável **idade**, responda: qual é a idade do conjunto de dados em que **70%** dos funcionários apresentam idade inferior?

In [48]:
idade_70 = df_wages['age'].quantile(0.70)
print(f"70% dos funcionários têm idade inferior a {idade_70} anos.")

70% dos funcionários têm idade inferior a 42.0 anos.

####j-) Analisando especificamente a variável **anos de experiência**, responda: qual é a quantidade de anos de experiência no conjunto de dados em que 10% dos funcionários ainda não possuem?

In [49]:
exp_90 = df_wages['experience_yrs'].quantile(0.90)
print(f"10% dos funcionários possuem mais de {exp_90} anos de experiência (logo, ainda não alcançaram esse valor inferior).")

10% dos funcionários possuem mais de 37.69999999999999 anos de experiência (logo, ainda não alcançaram esse valor inferior).

####k-) Calcule o desvio-padrão de cada um dos atributos: anos de educação, anos de experiência e idade.

In [50]:
desvios = df_wages[['education_yrs', 'experience_yrs', 'age']].std()
print("Desvio-Padrão:")
print(desvios)

Desvio-Padrão:
education_yrs      2.615373
experience_yrs    12.379710
age               11.726573
dtype: float64

####l-) Determine qual dos três atributos apresenta maior variabilidade: anos de educação, anos de experiência ou idade? Justifique a sua resposta.

In [51]:
cv = (df_wages[['education_yrs', 'experience_yrs', 'age']].std() / df_wages[['education_yrs', 'experience_yrs', 'age']].mean()) * 100
print("Coeficiente de Variação (%):")
print(cv)
atributo_maior_var = cv.idxmax()
print(f"\nO atributo com maior variabilidade é '{atributo_maior_var}' porque apresenta o maior Coeficiente de Variação.")

Coeficiente de Variação (%):
education_yrs     20.089312
experience_yrs    69.462700
age               31.836849
dtype: float64

O atributo com maior variabilidade é 'experience_yrs' porque apresenta o maior Coeficiente de Variação.

####m-) Leia o conjunto de dados [Atlas_Brasil_2014.csv](https://github.com/malegopc/DSBD/blob/main/Datasets/Atlas/Atlas_Brasil_2014.csv)

In [52]:
caminho_atlas = 'https://raw.githubusercontent.com/malegopc/DSBD/main/Datasets/Atlas/Atlas_Brasil_2014.csv'
df_atlas = pd.read_csv(caminho_atlas)
display(df_atlas.head())

  ESTADO  MORT1  ANOSEST  T_ANALF25M    RDPC     POPT   IDHM
0     RO  20.82     8.31       10.66  667.41  1641072  0.715
1     AC  18.37     7.95       17.19  548.24   762502  0.719
2     AM  19.38     9.21        8.06  579.45  3769444  0.709
3     RR  17.57     9.29        9.95  665.19   472758  0.732
4     PA  17.65     7.78       12.81  469.47  7615746  0.675

n-) Calcule a média do IDHM.

In [53]:
media_idhm = df_atlas['IDHM'].mean()
print(f"Média do IDHM: {media_idhm}")

Média do IDHM: 0.7376296296296296

o-) Qual é a taxa de mortalidade em que 50% dos estados apresentam taxa inferior?

In [54]:
mediana_mortalidade = df_atlas['MORT1'].median()
print(f"A taxa de mortalidade em que 50% dos estados apresentam taxa inferior é: {mediana_mortalidade}")

A taxa de mortalidade em que 50% dos estados apresentam taxa inferior é: 16.86

p-) Calcule qual o valor de RDPC (renda per capita) em que 25% dos estados apresentam valor superior.

In [55]:
rdpc_75 = df_atlas['RDPC'].quantile(0.75)
print(f"25% dos estados apresentam uma Renda Per Capita (RDPC) superior a: {rdpc_75}")

25% dos estados apresentam uma Renda Per Capita (RDPC) superior a: 885.165

q-) Determine dentre as duas variáveis: T_ANALF25M (Taxa de analfabetismo - 25 anos ou mais) ou RDPC (Renda per capita média), qual apresenta maior variabilidade. Justifique a sua resposta.

In [56]:
cols = ['T_ANALF25M', 'RDPC']
cv_atlas = (df_atlas[cols].std() / df_atlas[cols].mean()) * 100
print("Coeficiente de Variação (%):")
print(cv_atlas)

maior_var_atlas = cv_atlas.idxmax()
print(f"\nA variável com maior variabilidade é '{maior_var_atlas}', pois possui o maior Coeficiente de Variação, "
      "o que é a medida estatística correta para comparar a dispersão relativa de variáveis com naturezas e escalas numéricas distintas.")

Coeficiente de Variação (%):
T_ANALF25M    59.004758
RDPC          37.275119
dtype: float64

A variável com maior variabilidade é 'T_ANALF25M', pois possui o maior Coeficiente de Variação, o que é a medida estatística correta para comparar a dispersão relativa de variáveis com naturezas e escalas numéricas distintas.